<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8" />
    <title>Chọn Thời Gian - BeautyZone Spa</title>
    <jsp:include page="/WEB-INF/view/common/home/stylesheet.jsp"></jsp:include>
    
    <style>
        .time-container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        
        .time-card {
            background: white;
            border-radius: 12px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
            margin-bottom: 20px;
            overflow: hidden;
        }
        
        .time-header {
            background: linear-gradient(135deg, #c8945f 0%, #a67c4a 100%);
            color: white;
            padding: 24px;
            text-align: center;
        }
        
        .time-content {
            padding: 24px;
        }
        
        .date-picker {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            gap: 8px;
            margin-top: 16px;
        }
        
        .date-item {
            border: 2px solid #e5e7eb;
            border-radius: 8px;
            padding: 12px;
            text-align: center;
            cursor: pointer;
            transition: all 0.3s ease;
        }
        
        .date-item.selected {
            border-color: #c8945f;
            background-color: #fcf8f1;
        }
        
        .time-slots {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 12px;
            margin-top: 16px;
        }
        
        .time-slot {
            border: 2px solid #e5e7eb;
            border-radius: 8px;
            padding: 12px;
            text-align: center;
            cursor: pointer;
            transition: all 0.3s ease;
        }
        
        .time-slot.selected {
            border-color: #c8945f;
            background-color: #fcf8f1;
            color: #c8945f;
        }
        
        .btn {
            padding: 16px 24px;
            border: none;
            border-radius: 8px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s ease;
            text-decoration: none;
            text-align: center;
            display: inline-block;
            margin: 8px;
        }
        
        .btn-primary {
            background-color: #c8945f;
            color: white;
        }
        
        .btn-secondary {
            background-color: #6b7280;
            color: white;
        }
    </style>
</head>

<body id="bg">
    <div class="page-wraper">
        <!-- header -->
        <jsp:include page="/WEB-INF/view/common/home/header.jsp"></jsp:include>
        
        <!-- Content -->
        <div class="page-content bg-white">
            <!-- inner page banner -->
            <div class="dlab-bnr-inr overlay-primary bg-pt" 
                 style="background-image: url(${pageContext.request.contextPath}/assets/home/images/banner/bnr2.jpg);">
                <div class="container">
                    <div class="dlab-bnr-inr-entry">
                        <h1 class="text-white">Chọn Thời Gian</h1>
                    </div>
                </div>
            </div>
            
            <!-- Time selection content -->
            <div class="section-full content-inner">
                <div class="container">
                    <div class="time-container">
                        <div class="time-card">
                            <div class="time-header">
                                <h2>Chọn ngày và giờ</h2>
                            </div>
                            <div class="time-content">
                                <!-- Calendar Section -->
                                <div>
                                    <h4>Chọn ngày</h4>
                                    <div class="date-picker" id="datePicker">
                                        <!-- Dates will be generated by JavaScript -->
                                    </div>
                                </div>
                                
                                <!-- Time Slots Section -->
                                <div style="margin-top: 32px;">
                                    <h4>Chọn giờ</h4>
                                    <div class="time-slots" id="timeSlots">
                                        <!-- Time slots will be generated by JavaScript -->
                                    </div>
                                </div>
                                
                                <!-- Action Buttons -->
                                <div style="text-align: center; margin-top: 32px;">
                                    <a href="${pageContext.request.contextPath}/process-booking/therapist-selection" class="btn btn-secondary">
                                        Quay lại
                                    </a>
                                    <button type="button" id="continueBtn" class="btn btn-primary" disabled>
                                        Tiếp tục thanh toán
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Footer -->
        <jsp:include page="/WEB-INF/view/common/home/footer.jsp"></jsp:include>
    </div>
    
    <!-- JavaScript -->
    <jsp:include page="/WEB-INF/view/common/home/js.jsp"></jsp:include>
    <script src="${pageContext.request.contextPath}/assets/home/js/booking-storage.js"></script>
    
    <script>
        let selectedDate = null;
        let selectedTime = null;
        
        document.addEventListener('DOMContentLoaded', function() {
            initializeCalendar();
            generateTimeSlots();
        });
        
        function initializeCalendar() {
            const today = new Date();
            const datePicker = document.getElementById('datePicker');
            
            // Generate next 14 days
            for (let i = 1; i <= 14; i++) {
                const date = new Date(today);
                date.setDate(today.getDate() + i);
                
                const dateItem = document.createElement('div');
                dateItem.className = 'date-item';
                dateItem.dataset.date = date.toISOString().split('T')[0];
                dateItem.textContent = date.getDate() + '/' + (date.getMonth() + 1);
                dateItem.addEventListener('click', () => selectDate(dateItem));
                datePicker.appendChild(dateItem);
            }
        }
        
        function generateTimeSlots() {
            const timeSlotsContainer = document.getElementById('timeSlots');
            const timeSlots = ['08:00', '09:00', '10:00', '11:00', '14:00', '15:00', '16:00', '17:00'];
            
            timeSlots.forEach(time => {
                const timeSlot = document.createElement('div');
                timeSlot.className = 'time-slot';
                timeSlot.textContent = time;
                timeSlot.dataset.time = time;
                timeSlot.addEventListener('click', () => selectTime(timeSlot));
                timeSlotsContainer.appendChild(timeSlot);
            });
        }
        
        function selectDate(dateElement) {
            document.querySelectorAll('.date-item.selected').forEach(item => {
                item.classList.remove('selected');
            });
            
            dateElement.classList.add('selected');
            selectedDate = dateElement.dataset.date;
            updateContinueButton();
        }
        
        function selectTime(timeElement) {
            document.querySelectorAll('.time-slot.selected').forEach(item => {
                item.classList.remove('selected');
            });
            
            timeElement.classList.add('selected');
            selectedTime = timeElement.dataset.time;
            updateContinueButton();
        }
        
        function updateContinueButton() {
            const continueBtn = document.getElementById('continueBtn');
            if (selectedDate && selectedTime) {
                continueBtn.disabled = false;
                continueBtn.onclick = saveTimeAndProceed;
            } else {
                continueBtn.disabled = true;
            }
        }
        
        function saveTimeAndProceed() {
            // Save to browser storage
            if (window.BookingStorage) {
                window.BookingStorage.saveSelectedDateTime(selectedDate, selectedTime);
            }
            
            // Save to server session
            const formData = new FormData();
            formData.append('selectedDate', selectedDate);
            formData.append('selectedTime', selectedTime);
            
            fetch('${pageContext.request.contextPath}/process-booking/save-time', {
                method: 'POST',
                body: formData,
                credentials: 'same-origin'
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    window.location.href = '${pageContext.request.contextPath}/process-booking/payment';
                } else {
                    alert('Lỗi lưu thời gian');
                }
            })
            .catch(error => {
                console.error('Error saving time:', error);
                alert('Lỗi lưu thời gian');
            });
        }
    </script>
</body>
</html> 